version: '3.8'

services:
  frontend:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yogesh05
      - DB_NAME=Kgcarv2

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yogesh05
      POSTGRES_DB: Kgcarv2
    volumes:
      - Kgcarv2:/var/lib/postgresql/data
      - ./init-combined.sql:/docker-entrypoint-initdb.d/init-combined.sql
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"  # Access pgAdmin at http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  

volumes:
  pgadmin_data:
  Kgcarv2:
