version: '3.8'

services:
  frontend:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yogesh05
      - DB_NAME=Kgcarv2

    db:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: your_password
        POSTGRES_USER: postgres
        POSTGRES_DB: your_database_name
      volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      ports:
        - "5432:5432"
volumes:
  postgres-data:
